server {
  listen 8080;
  server_name localhost;

  location / {
    root /etc/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:html|json)$ {
    expires -1;
  }

  location ~* \.(?:css|js)$ {
    expires 1y;
    add_header Cache-Control "public, no-transform";
  }

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}
